-- com_serviceproject install SQL file.  This file inserts the default data
-- version 1.0.0
-- http://cbconnector.com

-- Fill in default Project Categories
INSERT INTO `#__serviceproject_project_categories` (`title`, `ordering`) VALUES
	('Serve', 1),
	('Fix-It', 2),
	('Clean-It', 3),
	('Build-It', 4),
	('Donate', 5),
	('Sort', 6),
	('Kindness', 7),
	('Arts//Crafts', 8),
	('Outside', 9),
	('Inside', 10),
	('Other', 11);

-- Fill in default Project Skills
INSERT INTO `#__serviceproject_project_skills` (`title`, `ordering`) VALUES
	('Painting', 1),
	('Cleaning', 2),
	('Yardwork', 3),
	('Light Construction', 4),
	('Crafts', 5),
	('Visiting', 6),
	('Food Prep', 7),
	('Delivery', 8);

-- Fill in default Project Age Ranges
INSERT INTO `#__serviceproject_project_ageranges` (`title`, `ordering`) VALUES
	('Under 5 Years of Age', 1),
	('Ages 5 - 11', 2),
	('Ages 12 - 15', 3),
	('Ages 16+', 4),
	('Other', 5);

-- Fill in default Update Reasons
INSERT INTO `#__serviceproject_updatereasons` (`updatereason_id`, `updatereason`, `updatetype`, `ordering`, `published`, `systemid`) VALUES
	(100, 'COM_SERVICEPROJECT_UR_NEWPROFILE', 'profile', 1, 1, -1),
	(110, 'COM_SERVICEPROJECT_UR_EDITNAME', 'profile', 2, 1, -1),
	(111, 'COM_SERVICEPROJECT_UR_EDITADDRESS', 'profile', 3, 1, -1),
	(112, 'COM_SERVICEPROJECT_UR_EDITEMAIL', 'profile', 4, 1, -1),
	(113, 'COM_SERVICEPROJECT_UR_EDITPHONE', 'profile', 5, 1, -1),
	(114, 'COM_SERVICEPROJECT_UR_EDITBIRTHDATE', 'profile', 6, 1, -1),
	(115, 'COM_SERVICEPROJECT_UR_SPLITADDRESS', 'profile', 7, 1, 1001),
	(116, 'COM_SERVICEPROJECT_UR_MERGEADDRESS', 'profile', 8, 1, 1002),
	(117, 'COM_SERVICEPROJECT_UR_STATECHANGEPROFILE', 'profile', 9, 1, 1003),
	(118, 'COM_SERVICEPROJECT_UR_MERGEPROFILE', 'profile', 10, 1, 1004),
	(119, 'COM_SERVICEPROJECT_UR_COPYPROFILE', 'profile', 11, 1, 1005),
	(120, 'COM_SERVICEPROJECT_UR_DELETEPROFILE', 'profile', 12, 1, 1006),
	(200, 'COM_SERVICEPROJECT_UR_NEWADDRESS', 'address', 1, 1, -1),
	(201, 'COM_SERVICEPROJECT_UR_ADDGEOCODES', 'address', 2, 1, -1),
	(210, 'COM_SERVICEPROJECT_UR_EDITADDRESS', 'address', 3, 1, -1),
	(211, 'COM_SERVICEPROJECT_UR_EDITGEOCODES', 'address', 4, 1, -1),
	(212, 'COM_SERVICEPROJECT_UR_SPLITADDRESS', 'address', 5, 1, 2001),
	(213, 'COM_SERVICEPROJECT_UR_MERGEADDRESS', 'address', 6, 1, 2002),
	(214, 'COM_SERVICEPROJECT_UR_COPYADDRESS', 'address', 7, 1, 2003),
	(215, 'COM_SERVICEPROJECT_UR_DELETEADDRESS', 'address', 8, 1, 2004),
	(216, 'COM_SERVICEPROJECT_UR_STATECHANGEADDRESS', 'address', 9, 1, 2005),
	(300, 'COM_SERVICEPROJECT_UR_NEWEVENTGROUP', 'eventgroup', 1, 1, -1),
	(301, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPDESCRIPTION', 'eventgroup', 2, 1, -1),
	(302, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPSTARTEND', 'eventgroup', 3, 1, -1),
	(303, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPREGISTRATION', 'eventgroup', 4, 1, -1),
	(304, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPPUBLISHDATES', 'eventgroup', 5, 1, -1),
	(400, 'COM_SERVICEPROJECT_UR_NEWEVENTGROUPSHIFT', 'eventgroupshift', 1, 1, -1),
	(401, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPSHIFT', 'eventgroupshift', 2, 1, -1),
	(402, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPSHIFTSTARTEND', 'eventgroupshift', 3, 1, -1),
	(403, 'COM_SERVICEPROJECT_UR_EDITEVENTGROUPSHIFTPUBLISHED', 'eventgroupshift', 4, 1, -1),
	(404, 'COM_SERVICEPROJECT_UR_COPYEVENTGROUPSHIFT', 'eventgroupshift', 5, 1, 3001);

-- Fill in default Project Roles
INSERT INTO `#__serviceproject_projectroles` ( `role_id`, `role_level`, `role`, `description`, `canmodifyproject`, `canmodifyvolunteers`, `canviewcontactinfo`, `rolelevelscanassign`, `published`, `ordering`, `systemid`) VALUES
	( 0, 0, 'COM_SERVICEPROJECT_ROLE_SUBMITTER', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_SUBMITTER', 0, 0, 0, '', 1, 1, 1000),
	( 100, 1, 'COM_SERVICEPROJECT_ROLE_ADMINISTRATOR', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_ADMINISTRATOR', 1, 1, 1, '2, 3, 4, 5', 1, 2, 1001),
	( 200, 2, 'COM_SERVICEPROJECT_ROLE_PROJECTMANAGER', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_PROJECTMANAGER', 1, 1, 1, '3, 4, 5', 1, 3, 2001),
	( 300, 3, 'COM_SERVICEPROJECT_ROLE_PROJECTFOREMAN', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_PROJECTFOREMAN', 1, 1, 1, '4, 5', 1, 4, 3001),
	( 400, 4, 'COM_SERVICEPROJECT_ROLE_PROJECTCOFOREMAN', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_PROJECTCOFOREMAN', 1, 1, 1, '5', 1, 5, 4001),
	( 500, 5, 'COM_SERVICEPROJECT_ROLE_VOLUNTEERCOORDINATOR', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_VOLUNTEERCOORDINATOR', 0, 1, 1, '', 1, 6, 5001),
	( 1000, 10, 'COM_SERVICEPROJECT_ROLE_ATTENDEE', 'COM_SERVICEPROJECT_ROLE_DESCRIPTION_ATTENDEE', 0, 0, 0, '', 1, 7, 10001);

-- Fill in default Registration Status
INSERT INTO `#__serviceproject_registrationstatus` (`status_id`, `status`, `description`, `counted`, `published`, `ordering`, `systemid` ) VALUES
	(100, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_REGISTERED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_REGISTERED', 1, 1, 1, 1001),
	(101, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_REGISTERED_NOTCOUNTED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_REGISTERED_NOTCOUNTED', 0, 1, 2, 1002),
	(102, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_ONWAITLIST', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_ONWAITLIST', 0, 1, 3, 1003),
	(103, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_AWAITINGAPPROVAL', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_AWAITINGAPPROVAL', 0, 1, 4, 1004),
	(104, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_AWAITINGPROFILESAPPROVAL', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_AWAITINGPROFILESAPPROVAL', 0, 1, 5, 1005),
	(105, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_ASSIGNED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_ASSIGNED', 1, 1, 6, 1006),
	(106, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_ASSIGNED_NOTCOUNTED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_ASSIGNED_NOTCOUNTED', 0, 1, 7, 1007),
	(200, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_ATTENDED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_ATTENDED', 1, 1, 8, 2001),
	(201, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_ATTENDED_NOTCOUNTED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_ATTENDED_NOTCOUNTED', 0, 1, 9, 2002),
	(300, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_NOSHOW', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_NOSHOW', 0, 1, 10, 3001),
	(301, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_REJECTED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_REJECTED', 0, 1, 11, 3002),
	(400, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_CANCELLED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_CANCELLED', 0, 1, 12, 4001),
	(401, 'COM_SERVICEPROJECT_REGISTRATION_STATUS_EXPIRED', 'COM_SERVICEPROJECT_REGISTRATION_STATUS_DESCRIPTION_EXPIRED', 0, 1, 13, 4002);
